name: Deploy Javadocs to Pages

on:
  push:
    branches: ["2.X"]
    paths:
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/main/**.kt'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          git-config-name: github-actions
          git-config-email: github-actions@github.com
          token: ${{ secrets.REMOTE_GH_PAGES_REPO_PAT }}
          repository-name: freya022/JavadocWikiTest-Pages
          folder: ./target/site/apidocs
          target-folder: docs
