name: Deploy Javadocs to Pages

on:
  push:
    branches: ["2.X"]
    paths:
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/main/**.kt'
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3.13.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          git-config-name: GitHub Actions
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
          ssh-key: ${{ secrets.REMOTE_GH_PAGES_REPO_SSH_KEY }}
          repository-name: freya022/JavadocWikiTest-Pages
          folder: ./target/site/apidocs
          target-folder: docs
