name: Deploy Javadocs to Pages

on:
  push:
    branches: ["2.X"]
    paths:
      - 'pom.xml'
      - 'src/main/**.java'
      - 'src/main/**.kt'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Generate Javadocs
        run: mvn -B javadoc:javadoc
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          folder: ./target/site/apidocs
          repository-name: JavadocWikiTest-Pages
          token: ${{ secrets.REMOTE_GH_PAGES_REPO_PAT }}
          target-folder: docs
