name: Deploy wiki to Pages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The BotCommands version this wiki deployment is for'
        required: true
      alias:
        description: 'The version alias for this deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - 2.X
          - 3.X

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure Git user
        run: |
          git config user.name GitHub Actions
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      # https://github.com/marketplace/actions/webfactory-ssh-agent#support-for-github-deploy-keys
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.REMOTE_GH_PAGES_REPO_SSH_KEY }}
      - name: Add pages remote
        run: |
          git remote add staging-remote git@github.com:freya022/JavadocWikiTest-Pages.git
          git fetch staging-remote staging --depth=1
          
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install Python dependencies
        working-directory: ./wiki
        run: pip install -r requirements.txt
      - name: Generate wiki
        working-directory: ./wiki
        run: mike deploy ${{ inputs.version }} ${{ inputs.alias }} --update-aliases --branch staging
      # The wiki is uploaded in the staging repository root
      - name: Push to staging repository
        run: |
          git push staging-remote staging
  deploy:
    needs: staging
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    runs-on: ubuntu-latest
    steps:
      # The entire staging repository (docs + wiki) gets deployed
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.REMOTE_GH_PAGES_REPO_SSH_KEY }}
          repository: freya022/JavadocWikiTest-Pages
          ref: staging
      - name: Upload staging repository
        uses: actions/upload-pages-artifact@v2
        with:
          # Upload entire repository
          path: .
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
