name: Deploy wiki to Pages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The BotCommands version this wiki deployment is for'
        required: true
      alias:
        description: 'The version alias for this deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - 2.X
          - 3.X

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      # https://github.com/marketplace/actions/webfactory-ssh-agent#support-for-github-deploy-keys
      - uses: webfactory/ssh-agent@v0.8.0
        with:
            ssh-private-key: ${{ secrets.REMOTE_GH_PAGES_REPO_SSH_KEY }}
      - name: Add pages remote
        run: |
          git remote add pages-remote git@github.com:freya022/JavadocWikiTest-Pages.git
          git fetch pages-remote gh-pages --depth=1
          
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.x
          cache: 'pip'
      - name: Install Python dependencies
        working-directory: ./wiki
        run: pip install -r requirements.txt
      - name: Generate wiki
        working-directory: ./wiki
        run: mike deploy ${{ inputs.version }} ${{ inputs.alias }} --update-aliases --deploy-prefix wiki
      - name: Push wiki
        run: |
          git push pages-remote HEAD:gh-pages
