name: Deploy wiki to Pages
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The BotCommands version this wiki deployment is for'
        required: true
      alias:
        description: 'The version alias for this deployment'
        required: true
        default: 'dev'
        type: choice
        options:
          - 2.X
          - 3.X

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GIT_TOKEN: ${{ secrets.REMOTE_GH_PAGES_REPO_PAT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Add pages remote
        run: |
          git config credential.helper '!f() { echo username=author; echo "password=$GIT_TOKEN"; };f'
          git remote add pages-remote https://github.com/freya022/JavadocWikiTest-Pages
          git fetch pages-remote gh-pages --depth=1
      - name: Configure Git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          
      # - uses: actions/setup-python@v4.7.1
      #   with:
      #     python-version: 3.x
      #     cache: 'pip'
      # - run: pip install -r requirements.txt
      # - run: mike deploy ${{ inputs.version }} ${{ inputs.alias }} --update-aliases --remote pages-remote --prefix wiki --push
